### ISSUE TITLE
503! Service Unavailable 

### ISSUE THREAD

**Issue by abdulhannanali** [ijoosong/moto.host#3]
I would like to try this out but [moto.host](http://moto.host) is giving me 503 error.
![503 moto.host](https://i.imgur.com/cMaw0nI.png)

**Comment by ijoosong** [comment]
Hmm, it's probably because it's not being hosted anywhere.  If you run it
locally, you might be able to get some stuff running!

On Wed, May 18, 2016 at 12:04 PM, Hannan Ali notifications@github.com
wrote:

> I would like to try this out but moto.host is giving me 503 error.
> 503 moto.host https://i.imgur.com/cMaw0nI.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ijoosong/moto.host/issues/3

## 

Jihun Joseph Song

**Comment by cassidoo** [comment]
Hmm I just looked up our domain service and they shut our routes down, not sure why... sorry about that!   Definitely check out stuff locally! :)
